#!/bin/bash
set -e

echo "Running all tests..."
rails test \
  test/controllers/pages_controller_test.rb \
  test/controllers/application_controller_test.rb \
  test/channels/chat_channel_test.rb \
  test/models/page_test.rb \
  test/models/site_test.rb \
  test/controllers/sites_controller_test.rb \
  test/system/users_test.rb \
  test/system/chat_frontend_llamabot_test.rb

echo "All tests completed."