#!/usr/bin/env bash
set -e

# 1) pull in submodules on host
if [ ! -d "vendor/gems/llama_bot_rails/.git" ]; then
  git submodule sync
  git submodule update --init --recursive
fi


# only copy if needed
[ ! -f .env ] && cp .env.example .env

docker-compose up --build